CaseTracker/CaseTracker/urls.py
from django.contrib import admin
from django.urls import path
from Case import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), {'next_page': '/'}, name='logout'),
    path('case',views.case, name='case'),
    path('admin/', admin.site.urls),
    path('',views.index),
    path('add/', views.add, name='add'),
    path('delete/<int:pk>', views.delete, name='delete'),
]

CaseTracker/Case/models.py
from django.db import models

class caseoverview(models.Model):
    caseid = models.CharField(max_length=20)
    title = models.CharField(max_length=125)
    owner = models.CharField(max_length=125)
    catagory = models.CharField(max_length=20)
    subcatagory = models.CharField(max_length=20)
    status = models.CharField(max_length=10)
    progress = models.CharField(max_length=100)
    progressDetails = models.TextField()
    incidentReporter = models.CharField(max_length=50)
    incidentOwner = models.CharField(max_length=50)
    priority = models.CharField(max_length=10)
    dateCreated = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.caseid} {self.title}'



# Create your models here.

CaseTracker/Case/forms.py
from django import forms

class AddCase(forms.Form):
    caseid = forms.CharField(max_length=20)
    title = forms.CharField(max_length=125)
    owner = forms.CharField(max_length=125)
    catagory = forms.CharField(max_length=20)
    subcatagory = forms.CharField(max_length=20)
    status = forms.CharField(max_length=10)
    progress = forms.CharField(max_length=100)
    progressDetails = forms.CharField(widget=forms.Textarea)
    incidentReporter = forms.CharField(max_length=50)
    incidentOwner = forms.CharField(max_length=50)
    priority = forms.CharField(max_length=10)
    dateCreated = forms.DateTimeField()

CaseTracker/Case/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .models import caseoverview
from .forms import AddCase

# Create your views here.
def index(request):
    return render(request, 'case/index.html')


def case(request):
    entres = caseoverview.objects.all()
    return render(request, 'Case/case.html', {'entri': entres})


def add(request):
    if request.method == 'POST':
        form = AddCase(request.POST)

        if form.is_valid():
            caseid = form.cleaned_data['caseid']
            title = form.cleaned_data['title']
            owner = form.cleaned_data['owner']
            catagory = form.cleaned_data['catagory']
            subcatagory = form.cleaned_data['subcatagory']
            status = form.cleaned_data['status']
            progress = form.cleaned_data['progress']
            progressDetails = form.cleaned_data['progressDetails']
            #incidentReporter = {{ request.user.username }}
            incidentReporter = form.cleaned_data['incidentReporter']
            incidentOwner = form.cleaned_data['incidentOwner']
            priority = form.cleaned_data['priority']

            caseoverview.objects.create(
                caseid=caseid,
                title=title,
                owner=owner,
                catagory=catagory,
                subcatagory=subcatagory,
                status=status,
                progress=progress,
                progressDetails=progressDetails,
                incidentReporter=incidentReporter,
                incidentOwner=incidentOwner,
                priority=priority,
            ).save()

            return HttpResponseRedirect('/')

    else:
        form = AddCase()

    return render(request, 'Case/forms.html', {'form': form})



def delete(request,pk):
    if request.method == 'DELETE':
        entry = get_object_or_404(caseoverview, pk=pk)
        entry.delete()

    return HttpResponseRedirect('/')










CaseTracker/Case/templates/Case/_casedetails.html
<div class="contrainer">

<tr>
    <td button data-id="{{ case.id }}" onclick="deletecase(this)" type="button" >X</td>
    <td>{{ case.caseid }}</td>
    <td>{{ case.title }}</td>
    <td>{{ case.owner }}</td>
    <td>{{ case.catagory }}</td>
    <td>{{ case.subcatagory }}</td>
    <td>{{ case.status }}</td>
    <td>{{ case.progress }}</td>
    <td>{{ case.progressDetails }}</td>
    <td>{{ case.incidentReporter }}</td>
    <td>{{ case.incidentOwner }}</td>
    <td>{{ case.priority }}</td>
    <td>{{ case.dateCreated|date }}</td>
    </tr>




</div>

CaseTracker/Case/templates/Case/base.html
<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Case Tracker</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'Case/css/bootstrap.css' %}"/>
    <link rel="stylesheet" href="{% static 'Case/css/style.css' %}"/>
</head>
<body>
{% block content %}
{% endblock %}
<script src="{% static 'Case/js/case.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
    var csrf_token = '{{ csrf_token }}'
</script>
</body>
</html>

CaseTracker/Case/templates/Case/case.html
{% extends 'Case/base.html' %}
{% block content %}
<br>

<div class="container">
    <h1>Case Tracker</h1>
    <button type="button" onclick="window.location='{% url 'add' %}'" class="btn btn-success">Add</button>

        <table  border="1">
              <thead>
                <tr class="table-active">
                    <th scope="col"></th>
                    <th scope="col">Case Id</th>
                    <th scope="col">Title</th>
                    <th scope="col">Owner</th>
                    <th scope="col">Catagory</th>
                    <th scope="col">Sub Catagory</th>
                    <th scope="col">Status</th>
                    <th scope="col">Progress</th>
                    <th scope="col">Progress Details</th>
                    <th scope="col">Incident Reporter</th>
                    <th scope="col">Incident Owner</th>
                    <th scope="col">Priority</th>
                    <th scope="col">Date Created</th>
                </tr>
              </thead>

     {% for case in entri %}
        {% include 'Case/_casedetails.html' %}
     {% endfor %}
        </table>
</div>

{% endblock %}

CaseTracker/Case/templates/Case/forms.html
{% extends 'Case/base.html' %}
{% block content %}

<div class="container">
    <h2>Add a case</h2>

<form method="POST">
    {% csrf_token %}
<table>
    <tr><td><button type="submit">Save</button><button type="submit" onclick="window.location='case'">Back</button></td></tr>
    <tr><th><label for="id_caseid">Caseid:</label></th><td><input type="text" name="caseid" maxlength="20" required id="id_caseid"></td></tr>
    <tr><th><label for="id_title">Title:</label></th><td><input type="text" name="title" maxlength="125" required id="id_title"></td></tr>
    <tr><th><label for="id_owner">Owner:</label></th><td><input type="text" name="owner" maxlength="125" required id="id_owner"></td></tr>
    <tr><th><label for="id_catagory">Catagory:</label></th>
        <td>
        <select name="catagory" id="catagory" required id="id_catagory">
          <option value="Incident">Incident</option>
          <option value="Change Request">Change Request</option>
          <option value="Service Request">Service Request</option>
        </select>
        </td>
    </tr>
    <tr><th><label for="id_subcatagory">Catagory:</label></th>
        <td>
        <select name="subcatagory" id="subcatagory" required id="id_subcatagory">
          <option value="Manufacturing">Manufacturing</option>
          <option value="Finance">Finance</option>
          <option value="Distribution">Distribution</option>
          <option value="Development">Development</option>
          <option value="Permission">Permission</option>

        </select>
        </td>
    </tr>

    <tr><th><label for="id_status">Status:</label></th>
        <td>
        <select name="status" id="status" required id="id_status">
          <option value="Open">Open</option>
          <option value="Queued">Queued</option>
          <option value="Completed">Completed</option>
          <option value="Cancelled">Cancelled</option>
        </select>
        </td>
    </tr>
    <tr><th><label for="id_progress">Progress:</label></th><td><input type="text" name="progress" maxlength="100" required id="id_progress"></td></tr>
    <tr><th><label for="id_progressDetails">Progressdetails:</label></th><td><textarea name="progressDetails" cols="40" rows="10" required id="id_progressDetails">
    </textarea></td></tr>
    <tr><th><label for="id_incidentReporter">Incidentreporter:</label></th><td><input type="text" name="incidentReporter" maxlength="50" required id="id_incidentReporter"></td></tr>
    <tr><th><label for="id_incidentOwner">Incidentowner:</label></th><td><input type="text" name="incidentOwner" maxlength="50" required id="id_incidentOwner"></td></tr>
    <tr><th><label for="id_priority">Priority:</label></th><td><input type="text" name="priority" maxlength="10" required id="id_priority"></td></tr>
    <tr><th><label for="id_dateCreated">Datecreated:</label></th><td><input type="text" name="dateCreated" required id="id_dateCreated"></td></tr>
    </table>
</form>
    </div>

{% endblock %}

CaseTracker/Case/templates/Case/index.html
{% extends 'Case/base.html' %}
{% block content %}
<br>

<div class="page-center container">
    <h1>Case Tracker</h1>
    <button class="btn btn-success" onclick="window.location='login'">Login</button>
</div>

{% endblock %}